### ISSUE TITLE
Get user in header without js in client

### ISSUE THREAD

**Issue by frmjar** [vvo/iron-session#413]
Hi everyone,

I am doing some testing to see if I can use iron-session in a project that I have to do.

I need my app to work largely without JavaScript on the client.

I have been doing tests on the available example. Everything is working correctly as I want I have a problem with the issue of getting the user in the Header. Basically if I disable JavaScript, the different header options disappear.

It is logical, since they require a user to be displayed. I've been doing a lot of testing and I haven't seen a way to get the user without JavaScript in the client.

Is there any way to do it?
I don't know if I have explained myself correctly.

Thank you.

**Comment by vvo** [comment]
Hey there, the sessions on iron-session are encrypted and can only be decoded on the server. This is by design.

If you want to display the user somewhere on your application with JavaScript disabled then you should use https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering. See here for an example: https://github.com/vvo/iron-session/blob/main/examples/next.js/pages/profile-ssr.js

The only change you would have to make here is to pass the user down to your template/header.

There will be possibilities like getServerSideProps in app.js and server side component in the future I guess. See https://github.com/vercel/next.js/discussions/10874#discussion-229. But I have no idea how to implement this for now.

You can give it a try since server components seems to be in alpha on Next.js. See https://nextjs.org/docs/advanced-features/react-18.

Good luck!

**Comment by frmjar** [comment]
Thanks for the reply.
For now I don't want to use components in alpha state.
I was hoping to be able to use the user without having to pass it through the components (template / header).
