### ISSUE TITLE
`withAuth` pattern with `iron-session`?

### ISSUE THREAD

**Issue by deadcoder0904** [vvo/iron-session#421]
I like the pattern used on `next-auth` → https://next-auth.js.org/getting-started/client#custom-client-session-handling

Basically, the gist is to put `.auth = true` & then check it in `_app.tsx` like:

```jsx
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      {Component.auth ? (
        <Auth>
          <Component {...pageProps} />
        </Auth>
      ) : (
        <Component {...pageProps} />
      )}
    </SessionProvider>
  )
}

function Auth({ children }) {
  const { data: session, status } = useSession()
  const isUser = !!session?.user
  React.useEffect(() => {
    if (status === "loading") return // Do nothing while loading
    if (!isUser) signIn() // If not authenticated, force log in
  }, [isUser, status])

  if (isUser) {
    return children
  }

  // Session is being fetched, or no user.
  // If no user, useEffect() will redirect.
  return <div>Loading...</div>
}
```

Is there a way to do that in `iron-session`?

**Comment by Izhaki** [comment]
You can do just that if you want. Nothing stops you from adopting the same approach (just use `useUser` instead of `useSession` and follow the next-auth example).

But having looked at various implementations of it, I actually find the next-auth one rather lacking.

I took inspiration from [auth0's withAuthenticationRequired](https://github.com/auth0/auth0-react/#protect-a-route) to create a similar HOC called `withAccessRestrictions`. It is described in https://github.com/vvo/iron-session/issues/437, but relies on the session being a context. The code is [here](https://github.com/Izhaki/iron-session/blob/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code/lib/withAccessRestrictions.tsx) and you can easily modify it to use `useUser` instead of `useSession`. It is used like so:

```js
export default withAccessRestrictions({
  hasAccess: (user) => Boolean(user?.isLoggedIn),
  unauthorizedRedirect: "/login",
  loading: <div>Loading...</div>,
})(SgProfile);
```

I would vote against adding this to the library, because that's an increase of API surface with neither the problem space (what will it need to support), nor the solution space (how to do it - just think of `next-auth` vs `auth0` approaches) clear in my view. It should be part of the examples until there is a very clear case to make it a formal API. I did suggest to possibly add it to an improved example.

**Comment by hannanstd** [comment]
if you pass the session via app props, then when you are viewing the page source in the browser you can see the session as json in html source. 

https://stackoverflow.com/questions/69396462/how-to-remove-next-data-from-dom-in-nextjs
