### ISSUE TITLE
The requested module 'cookie' does not provide an export named 'parse'

### ISSUE THREAD

**Issue by walidsj** [vvo/iron-session#422]
I fresh installed next js with iron session example, but it shows like this when i run it.

![image](https://user-images.githubusercontent.com/50021257/143069011-f558c8d7-1e1c-4229-a873-238d86dc8cd1.png)

**Comment by ausgray10** [comment]
I'm guessing that your using next.js based on the output and if so the error seems to be caused by esmExternals being set to "loose" by default.
You would fix this by setting 
`experimental: {
    esmExternals: false,
  }`
in your next.config.js

At least, that's what fixed  the errors for me!

**Comment by ausgray10** [comment]
Came back to this as I didn't think setting an experimental feature was the best solution, so I looked into it and found that trying to tree shake the "cookie" module in iron-session/dist/index.mjs was the issue.
The solution seems to be changing 
`import { parse as parseCookie, serialize as serializeCookie } from "cookie";` 
to 
`import cookie from "cookie";`

Changing [this line](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L3) and using the "cookie.parse" and "cookie.serialize" functions at [158](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L158) [182](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L182) [204](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L204) Seems to fix the issue.  Shouldn't really have an impact on performance since the cookie module is so small anyway.

**Comment by ctrl-alt-deleted** [comment]
Same issue as  @walidsj 

i wonder if there are any plan to change how the cookie packages is doing it import?

**Comment by dharnarh** [comment]
> Came back to this as I didn't think setting an experimental feature was the best solution, so I looked into it and found that trying to tree shake the "cookie" module in iron-session/dist/index.mjs was the issue. The solution seems to be changing `import { parse as parseCookie, serialize as serializeCookie } from "cookie";` to `import cookie from "cookie";`
> 
> Changing [this line](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L3) and using the "cookie.parse" and "cookie.serialize" functions at [158](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L158) [182](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L182) [204](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L204) Seems to fix the issue. Shouldn't really have an impact on performance since the cookie module is so small anyway.

Seems this is a fix, I will make a PR based on this

**Comment by vvo** [comment]
Published a new release, thanks all
