### ISSUE TITLE
Make error more readable

### ISSUE THREAD

**Issue by deadcoder0904** [vvo/iron-session#424]
I had used `process.env.COOKIE_NAME` for `cookieName` but in `.env` file, I called it `COOKIENAME` without the underscore.

This led to the same error:

> Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session

It would have made sense if the error was `Error: iron-session: Bad usage. 'cookieName' or 'password' is 'undefined'` instead.

This confused me for a whole day & I wasn't able to debug the cause but it worked on other project. Finally, found the solution.

Probably a minor bug but still worth it imo :)

**Comment by Izhaki** [comment]
[This one big condition](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.ts#L99-L109) can be broken down into multiple conditions, each providing more specific error:

```ts
  if (
    !req ||
    !res ||
    !userSessionOptions ||
    !userSessionOptions.cookieName ||
    !userSessionOptions.password
  ) {
    throw new Error(
      `iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session`,
    );
  }
```

[The tests](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/src/index.test.ts) are fairly set for such change.

It's an easy fix, fancy submitting a PR?

**Comment by faces-of-eth** [comment]
+1 to this, just ran into it myself. Was not intuitive to figure out. Thanks for raising the issue here.

**Comment by geekasylum** [comment]
I've also just run into this... New setup of IronSession in existng project.   I read docs, followed instructions, added a SECRET to .env, and process.env.SECRET in sessionOptions,js but on a console log it was apparent that the 'password' was undefined. Spent some time pulling out my hair wondering why my env variable wasnt there. The solution was to simply stop the dev server and restart it (So that node would reload the new env varables).

This feature would also go toward speeding the resolution time for issues like #498  +1 from me too!
