### ISSUE TITLE
The session is not destroyed upon logging off

### ISSUE THREAD

**Issue by alex-marmot** [vvo/iron-session#530]
I am a maintainer of an old project which is using 
> "next": "11.1.2",
> "next-iron-session": "^4.2.0".

Recently company did a pentest which says that the project had an Insecure Session Management issue. 
In the report it says:
> The session is not destroyed upon logging off, allowing an attacker who has managed to obtain 
> the authentication cookie/token to use it freely until it expires in order to perform authenticated 
> requests.
> This vulnerability was tested by intercepting a valid request, logging off via browser and then 
> repeating the same request with the same authentication cookies.

and here is the code for logout:

> case "DELETE":
>          await req.session.destroy();
>          res.json(null);
>          break;

How can I fix this?

**Comment by vvo** [comment]
@alex-marmot interesting, this is the same mechanism and behavior than the default sessions of Ruby On Rails (https://api.rubyonrails.org/classes/ActionDispatch/Session/CookieStore.html).

iron-session sessions are stateless per default. which means when you destroy a session in iron-session, you're mostly clearing out the cookies.

There's nothing we can do unfortunately here, this is "by design" so hopefully you can live with that

**Comment by vvo** [comment]
More reading here: https://guides.rubyonrails.org/security.html#session-hijacking
