### ISSUE TITLE
Example of using iron-session with Fastify?

### ISSUE THREAD

**Issue by RIP21** [vvo/iron-session#538]
The library claims to be working with Fastify. Is there any example of how to do it?

Thanks.

**Comment by vvo** [comment]
@RIP21 There's none, this library is compatible with any server that uses Node.js IncomingMessage/ServerResponse classes. Is Fastify using something else?

**Comment by vvo** [comment]
Seems like fastify is using some custom things, I'll remove that sentence then. There's certainly a way to make it work but it will require some change in iron-session code I believe.

**Comment by moofoo** [comment]
On the subject of Fastify compatability:

The main thing is that, on the Fastify response object, 'headers' [is a function](https://www.fastify.io/docs/latest/Reference/Reply/#headersobject), not an instance of [Headers ](https://developer.mozilla.org/en-US/docs/Web/API/Headers) or something like it. 

I've only looked over this briefly, but It appears like this will only cause problems in three places (in core.ts, at least). Two of these are obvious:

https://github.com/vvo/iron-session/blob/566056747a3931d7c901cc1c9351dc2590dad7a4/src/core.ts#L166-L170

and 

https://github.com/vvo/iron-session/blob/566056747a3931d7c901cc1c9351dc2590dad7a4/src/core.ts#L227-L239

In terms of fixes, probably the easiest option is to make use of the [vanilla Server Response object ](https://www.fastify.io/docs/latest/Reference/Reply/#raw) Fastify puts on the `raw` prop of their response object.

The third problem is a little more subtle: 

https://github.com/vvo/iron-session/blob/566056747a3931d7c901cc1c9351dc2590dad7a4/src/core.ts#L183-L187

The Fastify response object doesn't have `headersSent` as a prop (it's on that `raw` object), so it blows past this check. The underlying issue, however,  is that because Fastify buffers modifications to Headers, I don't think you can rely on the value of `reply.raw.headersSent` to prevent unwanted executions of `addToCookies` if Fastify is calling the shots.

If it were me I'd just do something like:
```
.... 
const cookieValue = cookie.serialize(
            options.cookieName,
            seal,
            options.cookieOptions,
          );

          if (cookieValue.length > 4096) {
            throw new Error(
              `iron-session: Cookie length is too big ${cookieValue.length}, browsers will refuse it. Try to remove some data.`,
            );
          }

if(!`${res.getHeader("set-cookie")}`.includes(options.cookieName)) {
          addToCookies(cookieValue, res);
}
....
```
But that's assuming there is no valid reason for cookieName to already be present in the  'set-cookie' header before the corresponding seal is appended.

Hopeuflly this post is useful to someone. I'll have some free time mid October to work on a pull request, if things haven't already been resolved.

**Comment by codyfyi** [comment]
I was able to get around this by simply passing `req.raw` and `res.raw` to getIronSession. A custom plugin/middleware could create the session:

```
const session = await getIronSession(req.raw, res.raw, {
  cookieName: 'myapp_cookiename',
  password: 'complex_password_at_least_32_characters_long'
})
```
---
If pull request #558 is merged it might also be a fix, but I'm not sure.
