### ISSUE TITLE
v6 and Next 13 pages middleware

### ISSUE THREAD

**Issue by viachaslau-latushkin** [vvo/iron-session#663]
Hi!
Thank you for your work!

I faced with problem in v6: save() and destroy() not working before return in nextjs middleware.
And changes applying only on next tick or after reloading page or on new request to pages/api folder.

"iron-session": "^6.3.1",
"next": "13.2.4"

**Comment by viachaslau-latushkin** [comment]
> @viachaslau-latushkin ➡️ [vercel/next.js#49442 (comment)](https://github.com/vercel/next.js/issues/49442#issuecomment-1679807704)

Thank you!
But in this case cookie from middleware is not encrypted.

**Comment by viachaslau-latushkin** [comment]
@Thanaen in middleware I am trying to apply refresh token logic.
I get a new token and try to rewrite cookie with new encrypted (encrypted token) value.
Yes, applySetCookie really add new cookie from middleware and it exists in next steps.
But how get new encrypted value with help of iron-session which will be encrypted in middleware with help of sessionOptions.password and after decrypt this value in time of SSR or in Api Router handler?

**Comment by viachaslau-latushkin** [comment]
@arthurjdam
Thank you.
Nice solution.
And good point to read documentation from start to end.

**Comment by MalakJoseph** [comment]
As @arthurjdam solution, here's the updated version that worked for me. Hope it may save time for others.

This solution fixes the error `Cookies can only be modified in a Server Action or Route Handler` after calling the `await session.save()`.

middleware.ts
```ts
export default async function middleware(req: NextRequest) {
  const { isLoggedIn, exp } = await getSession();

  // Refresh Token Rotation
  if (isLoggedIn && exp && exp < Date.now() / 1000) {
    try {
      const newSession = await refreshToken();
      const sealed = await sealData(newSession, sessionOptions);
      const res = NextResponse.redirect(req.url);

      res.cookies.set({
        name: '[your-cookie-name]',
        value: sealed,
      });
      return res;
    } catch (e) {
      await logout();
    }
  }
  
  return NextResponse.next();
}
```

authActions.ts

```ts
export async function getSession() {
  return await getIronSession<User>(cookies(), sessionOptions);
}

export async function refreshToken() {
  const session = await getSession();
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BACKEND_BASE_URL}/user/refresh`,
    {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + session.refreshToken },
    }
  );
  const { accessToken, refreshToken } = await res.json();
  const newUser = jwt.decode(accessToken) as JwtPayload;

  session.userToken = accessToken;
  session.refreshToken = refreshToken;
  session.exp = newUser.exp;

  return session;
}
```
P.S. I'm assuming the interface of my `User` object is:
```ts
export interface User {
  id: string;
  isLoggedIn: boolean;
  name: string;
  userToken: string;
  refreshToken: string;
  exp: number | undefined;
}
```
I'm available for any further clarifications or inquiries...

**Comment by vurak** [comment]
Please correct me if I'm wrong because this is doing my head in. I know this is an old thread but its the most relevant one I can find.

I want to implement something similar, however I'm trying to avoid having the refresh token and the access token in the same session, which essentially means in the same cookie, no? Because iron-session uses a cookie (encrypted) to store the session on the client side. Because isn't the whole point of having a refresh token that you don't send it on every request like the access token? From what I can see here, if an attacker gets your cookie they got the whole pie, they can refresh tokens indefinitely and their session won't expire until the refresh token does. So you might as well just have an access token with an expiry of the refresh token, no? Am I missing something?

I have been trying to find a way to have the refresh token separate and only send it up to the refresh endpoint when we need a new token, my thinking being that the fewer times it gets sent around the less likely it is for an attacker to steal it, but maybe that's not an accurate assumption. If it isn't, then it still leaves me with the question of why a refresh token in the first place, as this is the only case I can think of for having one.

Please if someone could help me out and point out what I'm missing and how I should be thinking about this. Thanks.

**Comment by viachaslau-latushkin** [comment]
@vurak sorry, but in your difficult case, separate access and refresh token - not really good solution.
To avoid hack of encrypted cookie you can store secret inside some kind of vault tool and regenerate in every day, for example.
Also, you can additionally encrypt tokens with your own encryption before save in encrypted cookie.
Maybe make sense to store in cookie only access token. But refresh token store inside server's db.
But honestly, if you right now have so difficult question, may be you should use another way to store tokens. Inside web worker on client, for example.

**Comment by rifat-dhrubo** [comment]
@vurak I have implemented similar feature by having the refresh token encrypted in a separate cookie using the `sealData` from "iron-session." I made the refresh cookie also a server cookie like the access cookie. So, attacker can't really access it from the client side. Frankly, it's not ideal I would rather have the refresh token only on the server side but can't really do that in this project.

**Comment by rifat-dhrubo** [comment]
@vurak Not necessarily. The refresh cookie is http only. So, it so can only be accessed in server side and also it's encrypted. The only way for attackers to gain access is to have access to the server side and also break the encryption. I use middleware with an api route in next js for refresh token. 

When the access token expires, I redirect the request to the api route. That route checks if the user has a valid session if so refreshes the cookie and sends them back to the page.
